name: Prose lint checks
on:
  pull_request:
  push:

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@V27
    - name: Vale
      run: nix-shell --run "vale maintainers source"
